 * Serving Flask app "index" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 248-973-167
27.5.111.134 - - [06/Sep/2018 18:12:59] "GET /model HTTP/1.1" 200 -
27.5.111.134 - - [06/Sep/2018 18:13:00] "GET /get_instruction_data HTTP/1.1" 200 -
27.5.111.134 - - [06/Sep/2018 18:13:07] "GET /model HTTP/1.1" 200 -
27.5.111.134 - - [06/Sep/2018 18:13:08] "GET /get_instruction_data HTTP/1.1" 200 -
27.5.110.115 - - [06/Sep/2018 18:14:25] "POST /api/instruction_module HTTP/1.1" 200 -
27.5.110.115 - - [06/Sep/2018 18:16:41] "POST /api/instruction_module HTTP/1.1" 200 -
27.5.110.115 - - [06/Sep/2018 18:18:04] "POST /api/instruction_module HTTP/1.1" 200 -
27.5.110.115 - - [06/Sep/2018 18:27:10] "POST /api/instruction_module HTTP/1.1" 200 -
27.5.110.115 - - [06/Sep/2018 18:40:23] "POST /api/instruction_module HTTP/1.1" 200 -
27.5.110.115 - - [06/Sep/2018 18:41:46] "POST /api/instruction_module HTTP/1.1" 200 -
27.5.110.115 - - [06/Sep/2018 19:27:23] "POST /api/instruction_module HTTP/1.1" 200 -
27.5.110.115 - - [06/Sep/2018 19:29:00] "POST /api/instruction_module HTTP/1.1" 200 -
27.5.110.115 - - [06/Sep/2018 19:36:04] "POST /api/instruction_module HTTP/1.1" 200 -
27.5.111.134 - - [06/Sep/2018 19:54:55] "GET /video_training HTTP/1.1" 200 -
27.5.111.134 - - [06/Sep/2018 19:54:55] "GET /static/css/material-dashboard.css?v=2.1.0 HTTP/1.1" 304 -
27.5.111.134 - - [06/Sep/2018 19:54:55] "GET /static/demo/demo.css HTTP/1.1" 304 -
27.5.111.134 - - [06/Sep/2018 19:54:55] "GET /static/js/core/jquery.min.js HTTP/1.1" 304 -
27.5.111.134 - - [06/Sep/2018 19:54:55] "GET /static/js/core/popper.min.js HTTP/1.1" 304 -
27.5.111.134 - - [06/Sep/2018 19:54:55] "GET /static/js/core/bootstrap-material-design.min.js HTTP/1.1" 304 -
27.5.111.134 - - [06/Sep/2018 19:54:55] "GET /static/js/plugins/perfect-scrollbar.jquery.min.js HTTP/1.1" 304 -
27.5.111.134 - - [06/Sep/2018 19:54:55] "GET /static/js/plugins/chartist.min.js HTTP/1.1" 304 -
27.5.111.134 - - [06/Sep/2018 19:54:55] "GET /static/js/material-dashboard.min.js?v=2.1.0 HTTP/1.1" 304 -
27.5.111.134 - - [06/Sep/2018 19:54:55] "GET /static/demo/demo.js HTTP/1.1" 304 -
27.5.111.134 - - [06/Sep/2018 19:54:55] "GET /static/js/plugins/bootstrap-notify.js HTTP/1.1" 304 -
27.5.111.134 - - [06/Sep/2018 19:54:56] "GET /get_training_data HTTP/1.1" 200 -
27.5.111.134 - - [06/Sep/2018 19:54:56] "GET /static/img/sidebar-1.jpg HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:41:30] "GET /model HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/whizible.in/public_html/videos/index.py", line 836, in model
    con.commit()
OperationalError: (2006, 'MySQL server has gone away')
210.18.161.238 - - [07/Sep/2018 09:41:30] "GET /model?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:41:30] "GET /model?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:41:30] "GET /model?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:41:31] "GET /model?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:41:31] "GET /model?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:41:32] "GET /model HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/whizible.in/public_html/videos/index.py", line 836, in model
    con.commit()
OperationalError: (2006, 'MySQL server has gone away')
210.18.161.238 - - [07/Sep/2018 09:41:32] "GET /model?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:41:32] "GET /model?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:41:32] "GET /model?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:41:32] "GET /model?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:41:32] "GET /model?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:43:58] "GET /model HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/whizible.in/public_html/videos/index.py", line 836, in model
    con.commit()
OperationalError: (2006, 'MySQL server has gone away')
210.18.161.238 - - [07/Sep/2018 09:43:58] "GET /model?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:43:58] "GET /model?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:43:58] "GET /model?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:43:59] "GET /model?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:43:59] "GET /model?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:10] "GET /model HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/whizible.in/public_html/videos/index.py", line 836, in model
    con.commit()
OperationalError: (2006, 'MySQL server has gone away')
210.18.161.238 - - [07/Sep/2018 09:44:10] "GET /model?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:10] "GET /model?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:10] "GET /model?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:11] "GET /model?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:11] "GET /model?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:21] "GET /model HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/whizible.in/public_html/videos/index.py", line 836, in model
    con.commit()
OperationalError: (2006, 'MySQL server has gone away')
210.18.161.238 - - [07/Sep/2018 09:44:21] "GET /model?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:21] "GET /model?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:21] "GET /model?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:21] "GET /model?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:21] "GET /model?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:22] "GET /video_training HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/whizible.in/public_html/videos/index.py", line 583, in video_training
    con.commit()
OperationalError: (2006, 'MySQL server has gone away')
210.18.161.238 - - [07/Sep/2018 09:44:22] "GET /video_training?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:25] "GET /model HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/whizible.in/public_html/videos/index.py", line 836, in model
    con.commit()
OperationalError: (2006, 'MySQL server has gone away')
210.18.161.238 - - [07/Sep/2018 09:44:25] "GET /model?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:25] "GET /model?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:25] "GET /model?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:25] "GET /model?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:25] "GET /model HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/whizible.in/public_html/videos/index.py", line 836, in model
    con.commit()
OperationalError: (2006, 'MySQL server has gone away')
210.18.161.238 - - [07/Sep/2018 09:44:25] "GET /model?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:25] "GET /model?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:25] "GET /model?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:25] "GET /model HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/whizible.in/public_html/videos/index.py", line 836, in model
    con.commit()
OperationalError: (2006, 'MySQL server has gone away')
210.18.161.238 - - [07/Sep/2018 09:44:25] "GET /model?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:25] "GET /model?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:25] "GET /model?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:25] "GET /model?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:25] "GET /model HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/whizible.in/public_html/videos/index.py", line 836, in model
    con.commit()
OperationalError: (2006, 'MySQL server has gone away')
210.18.161.238 - - [07/Sep/2018 09:44:25] "GET /model?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:26] "GET /model?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:26] "GET /model?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:26] "GET /model?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:26] "GET /model?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:26] "GET /model?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:43] "GET /model HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/whizible.in/public_html/videos/index.py", line 836, in model
    con.commit()
OperationalError: (2006, 'MySQL server has gone away')
210.18.161.238 - - [07/Sep/2018 09:44:43] "GET /model?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:43] "GET /model?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:43] "GET /model?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:43] "GET /model HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/whizible.in/public_html/videos/index.py", line 836, in model
    con.commit()
OperationalError: (2006, 'MySQL server has gone away')
210.18.161.238 - - [07/Sep/2018 09:44:43] "GET /model?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:43] "GET /model?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:43] "GET /model?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:43] "GET /model?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:43] "GET /model HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/whizible.in/public_html/videos/index.py", line 836, in model
    con.commit()
OperationalError: (2006, 'MySQL server has gone away')
210.18.161.238 - - [07/Sep/2018 09:44:43] "GET /model?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:43] "GET /model?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:43] "GET /model?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:43] "GET /model?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:43] "GET /model HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/whizible.in/public_html/videos/index.py", line 836, in model
    con.commit()
OperationalError: (2006, 'MySQL server has gone away')
210.18.161.238 - - [07/Sep/2018 09:44:44] "GET /model?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:44] "GET /model?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:44] "GET /model?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:44] "GET /model?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:44:44] "GET /model?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/var/www/whizible.in/public_html/videos/index.py', reloading
new file
hhzhzh
ffgfg7
fff
ttetestest
jjjjjx
yyf
vvg
jjfjfjjfjd
ffg
aaf
ddudud
jjj
new file
hhzhzh
ffgfg7
fff
ttetestest
jjjjjx
yyf
vvg
jjfjfjjfjd
ffg
aaf
ddudud
jjj
nnj
new file
hhzhzh
ffgfg7
fff
ttetestest
jjjjjx
yyf
vvg
jjfjfjjfjd
ffg
aaf
ddudud
jjj
nnj
ddh
new file
hhzhzh
ffgfg7
fff
ttetestest
jjjjjx
yyf
vvg
jjfjfjjfjd
ffg
aaf
ddudud
jjj
nnj
ddh
jjf
new file
hhzhzh
ffgfg7
fff
ttetestest
jjjjjx
yyf
vvg
jjfjfjjfjd
ffg
aaf
ddudud
jjj
nnj
ddh
jjf
jmh
new file
hhzhzh
ffgfg7
fff
ttetestest
jjjjjx
yyf
vvg
jjfjfjjfjd
ffg
aaf
ddudud
jjj
nnj
ddh
jjf
jmh
rrf
new file
hhzhzh
ffgfg7
fff
ttetestest
jjjjjx
yyf
vvg
jjfjfjjfjd
ffg
aaf
ddudud
jjj
nnj
ddh
jjf
jmh
rrf
ffy
new file
hhzhzh
ffgfg7
fff
ttetestest
jjjjjx
yyf
vvg
jjfjfjjfjd
ffg
aaf
ddudud
jjj
nnj
ddh
jjf
jmh
rrf
ffy
jjhjhd
new file
hhzhzh
ffgfg7
fff
ttetestest
jjjjjx
yyf
vvg
jjfjfjjfjd
ffg
aaf
ddudud
jjj
nnj
ddh
jjf
jmh
rrf
ffy
jjhjhd
ffdfdu
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 248-973-167
210.18.161.238 - - [07/Sep/2018 09:45:25] "GET /model HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:45:25] "GET /static/css/material-dashboard.css?v=2.1.0 HTTP/1.1" 304 -
210.18.161.238 - - [07/Sep/2018 09:45:25] "GET /static/js/core/popper.min.js HTTP/1.1" 304 -
210.18.161.238 - - [07/Sep/2018 09:45:25] "GET /static/demo/demo.css HTTP/1.1" 304 -
210.18.161.238 - - [07/Sep/2018 09:45:25] "GET /static/js/material-dashboard.min.js?v=2.1.0 HTTP/1.1" 304 -
210.18.161.238 - - [07/Sep/2018 09:45:25] "GET /static/js/plugins/chartist.min.js HTTP/1.1" 304 -
210.18.161.238 - - [07/Sep/2018 09:45:25] "GET /static/js/core/jquery.min.js HTTP/1.1" 304 -
210.18.161.238 - - [07/Sep/2018 09:45:25] "GET /static/demo/demo.js HTTP/1.1" 304 -
210.18.161.238 - - [07/Sep/2018 09:45:25] "GET /static/js/plugins/bootstrap-notify.js HTTP/1.1" 304 -
210.18.161.238 - - [07/Sep/2018 09:45:25] "GET /static/js/core/bootstrap-material-design.min.js HTTP/1.1" 304 -
210.18.161.238 - - [07/Sep/2018 09:45:25] "GET /static/js/plugins/perfect-scrollbar.jquery.min.js HTTP/1.1" 304 -
210.18.161.238 - - [07/Sep/2018 09:45:26] "GET /get_instruction_data HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 09:45:26] "GET /static/img/sidebar-1.jpg HTTP/1.1" 304 -
210.18.161.238 - - [07/Sep/2018 09:45:26] "GET /favicon.ico HTTP/1.1" 404 -
 * Detected change in '/var/www/whizible.in/public_html/videos/index.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 248-973-167
210.18.161.238 - - [07/Sep/2018 10:05:32] "GET / HTTP/1.1" 200 -
Successfully created the TFRecords: /var/www/whizible.in/public_html/videos/static/img/upload/video/training/23_step/data/test.record
Successfully created the TFRecords: /var/www/whizible.in/public_html/videos/static/img/upload/video/training/23_step/data/train.record
210.18.161.238 - - [07/Sep/2018 10:06:08] "POST /video_upload HTTP/1.1" 302 -
210.18.161.238 - - [07/Sep/2018 10:06:08] "GET /model HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 10:06:09] "GET /get_instruction_data HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 10:06:33] "GET /model HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 10:06:34] "GET /get_instruction_data HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 10:07:59] "GET /video_training HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 10:07:59] "GET /get_training_data HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 10:08:06] "POST /training_data_update HTTP/1.1" 200 -
Traceback (most recent call last):
  File "legacy/train.py", line 49, in <module>
    from object_detection.builders import dataset_builder
ImportError: No module named object_detection.builders
210.18.161.238 - - [07/Sep/2018 10:08:08] "GET /video_training HTTP/1.1" 200 -
210.18.161.238 - - [07/Sep/2018 10:08:08] "GET /get_training_data HTTP/1.1" 200 -
